### ISSUE TITLE
Game Crashes With Mod Enabled

### ISSUE THREAD

**Issue by MasterGamerY** [BeatACVR/geode-clicksound#13]
Whenever I try to exit a level with this mod enabled the game crashes (see attached crashlog). This doesn't happen when I disable the mod. Is there a way to fix this?
[2024-02-04_20-49-57.log](https://github.com/BeatACVR/geode-clicksound/files/14159510/2024-02-04_20-49-57.log)

**Comment by BeatACVR** [comment]
try downgrading node-ids to v1.1.4

**Comment by BeatACVR** [comment]
https://github.com/geode-sdk/NodeIDs/releases/download/v1.1.4/geode.node-ids.geode

**Comment by BeatACVR** [comment]
did it work?
