### ISSUE TITLE
Interesting oddity in Dual Mode

### ISSUE THREAD

**Issue by SevoStar** [BeatACVR/geode-clicksound#16]
For some reason, when in dual mode, the click sound plays twice. From what I'm guessing, this might be because there are two icons jumping, resulting in the sound playing twice.
If there is only one icon, the bug won't occur.

I have some footage linked here! 
https://github.com/BeatACVR/geode-clicksound/assets/144753006/9ce577dd-d3d3-4eed-ad4f-b3074cd4914e

This mod is still very good despite this bug in my opinion!

**Comment by BeatACVR** [comment]
already aware of this:3

**Comment by BeatACVR** [comment]
i dont know how to fix it
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by BeatACVR** [comment]
horizontally rotating fish

**Comment by ItzFlowerGMD** [comment]
> i dont know how to fix it aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

dumb fix: make click sound volume 50% so it adds back to 100%

**Comment by BeatACVR** [comment]
i dont think i can adjust volume like that

**Comment by BeatACVR** [comment]
i can do muted, normal volume, or louder volume, but thats all

**Comment by ItzFlowerGMD** [comment]
damn ok

**Comment by BeatACVR** [comment]
also this wouldnt work because sound doesnt work like that

**Comment by BeatACVR** [comment]
fixed, ty @Weebifying

**Comment by coopeeo** [comment]
weeb did it!

**Comment by Weebifying** [comment]
pensive
